Repository cms-sw/pkgtools, pull requests merged in 2020-06, with the labels that each got.

#158 use package_dependency for pip deps
  cmsBuild
  scheduler.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#159 [V00-33] use package_dependency for pip deps
  cmsBuild
  scheduler.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#160 Add option to store package deps
  cmsBuild
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, requires-external, tests-approved

#161 Add option to store package deps - pkgtools V33
  cmsBuild
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, tests-pending

#163 remove redundant option v33
  cmsBuild
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#162 Add docfile record only if the file exists - V32
  cmsBuild
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started
